
/****** Object:  Table [dbo].[XCUBE_MEASURES]    Script Date: 12/29/2008 20:22:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XCUBE_MEASURES](
	[Key] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Title] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FunctionClass] [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ValueFormatProvider] [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  CONSTRAINT [PK_XCUBE_MEASURES] PRIMARY KEY CLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[XCUBE_DIMENSIONS]    Script Date: 12/29/2008 20:22:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XCUBE_DIMENSIONS](
	[Key] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Title] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_XCUBE_DIMENSIONS] PRIMARY KEY CLUSTERED 
(
	[Key] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[XCUBE_DIMENSION_ELEMENTS]    Script Date: 12/29/2008 20:22:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XCUBE_DIMENSION_ELEMENTS](
	[ID] [varchar](900) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ParentID] [varchar](900) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DimensionKey] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Key] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Title] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[weight] [float] NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF

/****** Object:  Table [dbo].[XCUBE_DIMMAP]    Script Date: 01/07/2009 16:50:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XCUBE_DIMMAP](
	[DimMapKey] [varchar](255) NOT NULL,
	[Description] [text] NULL,
	[DimensionKey] [varchar](255) NOT NULL,
	[UnmappedPath] [varchar](900) NULL,
	[OnUnmapped] [varchar](50) NOT NULL CONSTRAINT [DF_XCUBE_DIMMAP_OnUnmapped]  DEFAULT ('CREATE'),
 CONSTRAINT [PK_XCUBE_DIMMAP] PRIMARY KEY CLUSTERED 
(
	[DimMapKey] ASC
) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[XCUBE_DIMMAP_ELEMENTS]    Script Date: 01/07/2009 16:50:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XCUBE_DIMMAP_ELEMENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DimMapKey] [varchar](255) NOT NULL,
	[Expression] [text]  NOT NULL,
	[isRegExp] [bit] NOT NULL,
	[IgnoreCase] [bit] NOT NULL,
	[ElementPath] [varchar](900) NULL,
	[SkipRecord] [bit] NOT NULL,
 CONSTRAINT [PK_XCUBE_DIMMAP_ELEMENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF